import { type FormEvent, useEffect, useRef, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { getSportActivities, saveSportActivity, type Sport } from "../api";
import { SportPicker } from "../components/SportPicker";

function localISODate(value = new Date()) { return `${value.getFullYear()}-${String(value.getMonth()+1).padStart(2,"0")}-${String(value.getDate()).padStart(2,"0")}`; }
function normalizeNumber(value: string) { const cleaned=value.replace(/[^0-9.,]/g,""); const separator=cleaned.search(/[.,]/); return separator<0?cleaned:cleaned.slice(0,separator+1)+cleaned.slice(separator+1).replace(/[.,]/g,""); }

export function SportActivityFormPage() {
  const params = useParams<{ dt?: string; sportKey?: string }>(); const navigate=useNavigate(); const editing=Boolean(params.dt&&params.sportKey);
  const [dt,setDT]=useState(params.dt??localISODate()); const [sport,setSport]=useState<Sport|null>(null); const [sets,setSets]=useState([""]); const [loading,setLoading]=useState(editing); const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const [fieldError,setFieldError]=useState("");
  const firstSetRef=useRef<HTMLInputElement>(null);
  useEffect(()=>{if(!params.dt||!params.sportKey)return;let cancelled=false;setLoading(true);void getSportActivities(params.dt,params.dt).then((items)=>{const item=items.find(value=>value.sport.key===params.sportKey);if(!item)throw new Error("Запись активности не найдена");if(!cancelled){setSport(item.sport);setSets(item.sets.map(String));}}).catch((reason:unknown)=>{if(!cancelled)setError(reason instanceof Error?reason.message:"Не удалось загрузить активность");}).finally(()=>{if(!cancelled)setLoading(false);});return()=>{cancelled=true;};},[params.dt,params.sportKey]);
  async function submit(event:FormEvent){event.preventDefault();const values=sets.map(value=>Number(value.replace(",",".")));if(!dt||!sport||values.length===0||values.some(value=>!Number.isFinite(value)||value<=0)){setFieldError("Укажите дату, вид спорта и положительные значения всех подходов");return;}setSaving(true);setError("");try{await saveSportActivity({dt,sportKey:sport.key,sets:values});navigate("/sport-activity");}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось сохранить активность");}finally{setSaving(false);}}
  return <div className="page food-form-page"><Link className="back-link" to="/sport-activity">← К активности</Link><header className="form-page-header"><p className="eyebrow">{editing?"Редактирование":"Новая запись"}</p><h1>{editing?"Изменить активность":"Добавить активность"}</h1></header>{loading?<p className="muted">Загрузка активности…</p>:<section className="food-form-card">{error&&<div className="error" role="alert">{error}</div>}<form noValidate onSubmit={submit}><label>Дата<input disabled={editing} type="date" value={dt} onChange={event=>setDT(event.target.value)}/></label><label>Вид спорта<SportPicker disabled={editing} value={sport} onError={setError} onSelect={(value)=>{setSport(value);setFieldError("");requestAnimationFrame(()=>firstSetRef.current?.focus());}}/></label><div className="set-fields">{sets.map((value,index)=><label key={index}>Подход {index+1}<span><input ref={index===0?firstSetRef:undefined} aria-label={`Подход ${index+1}`} inputMode="decimal" value={value} onChange={event=>setSets(sets.map((current,currentIndex)=>currentIndex===index?normalizeNumber(event.target.value):current))}/>{sets.length>1&&<button aria-label={`Удалить подход ${index+1}`} className="text-button danger" type="button" onClick={()=>setSets(sets.filter((_,currentIndex)=>currentIndex!==index))}>×</button>}</span></label>)}</div>{fieldError&&<span className="field-error" role="alert">{fieldError}</span>}<button className="button secondary" type="button" onClick={()=>setSets([...sets,""])}>Добавить подход</button><div className="form-actions"><button className="button primary" disabled={saving}>{saving?"Сохраняем…":"Сохранить"}</button><Link className="button secondary" to="/sport-activity">Отмена</Link></div></form></section>}</div>;
}
